### ISSUE TITLE
Some os commands (ls, ping...) not working after bootstrap

### ISSUE THREAD

**Issue by fleveque** [holman/dotfiles#281]
I'm having some trouble with my forked repo on my macOS Sierra. After installing, some commands like _ls_ or _ping_ don't work:

> 🔌  1:11 in .dotfiles/ on master 
> › ls
> Traceback (most recent call last):
>   File "/usr/local/Cellar/grc/1.10_1/libexec/bin/grc", line 191, in <module>
>     os.execvp(args[0], args)
>   File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/os.py", line 559, in execvp
>     _execvpe(file, args)
>   File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/os.py", line 604, in _execvpe
>     raise last_exc.with_traceback(tb)
>   File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/os.py", line 594, in _execvpe
>     exec_func(fullname, *argrest)
> FileNotFoundError: [Errno 2] No such file or directory

Does anybody have a clue about what could be the problem?

**Comment by samuelleach** [comment]
It seems to be related to https://github.com/garabik/grc/issues/54

**Comment by justin-vanwinkle** [comment]
`ls` is the alias of a command.  Here is where it is defined.
https://github.com/holman/dotfiles/blob/master/system/aliases.zsh

If you have any additional commands that don't work as you expect, look through the other alias files for that command.
